Neos:
  EventSourcedContentRepository:
    testing:
      projectorsToBeReset:
        'Neos\ContentGraph\PostgreSQLAdapter\Domain\Projection\HypergraphProjector': true
    projection:
      projectorsToBeBlocked:
        'Neos\ContentGraph\PostgreSQLAdapter\Domain\Projection\HypergraphProjector': true
