Neos:
  EventSourcing:
    EventStore:
      stores:
        'DISABLEDContentRepository':
          storage: 'Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage'
          listeners:
            'Neos\ContentGraph\PostgreSQLAdapter\.*': true
