name: Tests

on:
  push:
    branches: [ main, '[0-9]+.[0-9]' ]
  pull_request:
    branches: [ main, '[0-9]+.[0-9]' ]
  workflow_dispatch: # Allow manual triggering on any branch via `gh workflow run tests.yml -r branch-name`

jobs:
  build:
    env:
      FLOW_CONTEXT: Testing
      FLOW_PATH_ROOT: ../neos-base-distribution

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: "8.2"
            neos-version: "9.0"
            # comment in this line to use a specific branch of the neos dev collection
            # neos-dev-collection-branch: "bugfix/my-branch"

          - php-version: "8.2"
            neos-version: "9.0"
            # comment in this line to use a specific branch of the neos dev collection
            neos-dev-collection-branch: "bugfix/postgres-compatibility-except-graph"
            # wip, also test Neos.Neos projections alongside
            include-neos-neos-content-repository-preset: true

    services:
      postgres:
        # see https://www.postgresql.org/support/versioning/
        # this should be a current release
        image: postgres:18.3
        env:
          POSTGRES_USER: neos
          POSTGRES_PASSWORD: neos
          POSTGRES_DB: neos_behaviour_testing
          POSTGRES_ROOT_PASSWORD: neos
        ports:
          - "5432:5432"
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite, mysql

      - id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Prepare Neos distribution
        run: |
          git clone --depth 1 --branch ${{ matrix.neos-version }} https://github.com/neos/neos-development-distribution.git ${FLOW_PATH_ROOT}
          cd ${FLOW_PATH_ROOT}
          
          ${{ matrix.neos-dev-collection-branch &&
              format('composer require --no-update --no-interaction "neos/neos-development-collection:dev-{0} as {1}.x-dev"', matrix.neos-dev-collection-branch, matrix.neos-version)
          }}

          composer config --no-plugins allow-plugins.neos/composer-plugin true
          
          composer config repositories.package '{ "type": "path", "url": "../contentgraph-postgresqladapter", "options": { "symlink": false } }'
          composer require --no-update --no-interaction neos/contentgraph-postgresqladapter:@dev
          
          composer require --dev --no-update --no-interaction phpstan/phpstan:^1.10

      - name: Install dependencies
        run: |
          cd ${FLOW_PATH_ROOT}
          rm -rf composer.lock
          composer install --no-interaction --no-progress --prefer-dist

      - name: Linting
        run: |
          cd ${FLOW_PATH_ROOT}
          bin/phpstan analyse Packages/Libraries/neos/contentgraph-postgresqladapter --level 8

      # - name: Run Unit tests
      #   run: |
      #     cd ${FLOW_PATH_ROOT}
      #     bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Libraries/neos/contentgraph-postgresqladapter/Tests/Unit

      - name: Setup Flow configuration
        run: |
          cd ${FLOW_PATH_ROOT}
          rm -f Configuration/Testing/Settings.yaml
          
          # unset the Neos.Neos default in the upper context 
          ${{ matrix.include-neos-neos-content-repository-preset && '' || '
          cat <<EOF >> Configuration/Settings.yaml
          Neos:
            ContentRepositoryRegistry:
              presets:
                default: ~
          EOF' }}
          
          cat <<EOF >> Configuration/Testing/Settings.yaml
          Neos:
            Flow:
              persistence:
                backendOptions:
                  host: '127.0.0.1'
                  port: 5432
                  driver: pdo_pgsql
                  user: 'neos'
                  password: 'neos'
                  dbname: 'neos_behaviour_testing'
                  charset: 'utf8'
                  defaultTableOptions:
                    charset: 'utf8'

            ContentRepositoryRegistry:
              presets:
                default:
                  # if Neos.Neos preset is not used setup missing defaults in lower context, otherwise null
          ${{ matrix.include-neos-neos-content-repository-preset && '' || '
                  eventStore:
                    factoryObjectName: Neos\ContentRepositoryRegistry\Factory\EventStore\DoctrineEventStoreFactory
                  subscriptionStore:
                    factoryObjectName: Neos\ContentRepositoryRegistry\Factory\SubscriptionStore\SubscriptionStoreFactory
                  propertyConverters:
                    DateTimeNormalizer:
                      className: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
                    ScalarNormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\ScalarNormalizer
                    EnumNormalizer:
                      className: Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer
                    ArrayNormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\ArrayNormalizer
                    UriNormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\UriNormalizer
                    ValueObjectArrayDenormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\ValueObjectArrayDenormalizer
                    ValueObjectBoolDenormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\ValueObjectBoolDenormalizer
                    ValueObjectFloatDenormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\ValueObjectFloatDenormalizer
                    ValueObjectIntDenormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\ValueObjectIntDenormalizer
                    ValueObjectStringDenormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\ValueObjectStringDenormalizer
                    DoctrinePersistentObjectNormalizer:
                      className: Neos\ContentRepositoryRegistry\Infrastructure\Property\Normalizer\DoctrinePersistentObjectNormalizer
                    CollectionTypeDenormalizer:
                      className: Neos\ContentRepository\Core\Infrastructure\Property\Normalizer\CollectionTypeDenormalizer
                    ProxyAwareObjectNormalizer:
                      className: Neos\ContentRepositoryRegistry\Infrastructure\Property\Normalizer\ProxyAwareObjectNormalizer
            ' }}

                  contentGraphProjection:
                    factoryObjectName: Neos\ContentGraph\PostgreSQLAdapter\PostgresContentGraphProjectionFactory
          EOF

          cat <<EOF >> Configuration/Testing/Objects.yaml
          Neos\ContentGraph\PostgreSQLAdapter\PostgresContentGraphProjectionFactory:
            scope: singleton
            factoryObjectName: 'Neos\ContentRepositoryRegistry\Infrastructure\GenericObjectFactory'
            arguments:
              1:
                value: 'Neos\ContentGraph\PostgreSQLAdapter\PostgresContentGraphProjectionFactory'
              2:
                object: 'Doctrine\DBAL\Connection'

          Neos\ContentRepository\Core\Projection\ContentGraph\ProjectionIntegrityViolationDetectionRunnerFactoryInterface:
            scope: singleton
            factoryObjectName: Neos\ContentRepositoryRegistry\Infrastructure\GenericObjectFactory
            arguments:
              1:
                value: Neos\ContentGraph\PostgreSQLAdapter\PostgresProjectionIntegrityViolationDetectionRunnerFactory
              2:
                object: Doctrine\DBAL\Connection

          EOF

      - name: Run doctrine migrate
        # prevent db transaction in connection from being closed by migrating in advance
        run: |
          cd ${FLOW_PATH_ROOT}
          FLOW_CONTEXT=Testing/Behat ./flow doctrine:migrate --quiet

      - name: Run behat Neos.ContentRepository.BehavioralTests tests
        run: |
          cd ${FLOW_PATH_ROOT}
          FLOW_CONTEXT=Testing/Behat bin/behat -f progress --strict --no-interaction -c Packages/Neos/Neos.ContentRepository.BehavioralTests/Tests/Behavior/behat.yml.dist -vvv --stop-on-failure

      - name: Show log on failure
        if: ${{ failure()  }}
        shell: bash
        run: |
          cd ${FLOW_PATH_ROOT}
          # cat Data/Logs/System_Testing.log
          if compgen -G "Data/Logs/Exceptions/*" > /dev/null; then
            for file in Data/Logs/Exceptions/*; do
              echo $file
              cat $file
            done
          fi
